name: Smartcheck
origin: https://github.com/smartdec/smartcheck
info: Securify automatically checks for vulnerabilities and bad coding practices. It runs lexical and syntactical analysis on Solidity source code.
solidity:
    image: smartbugs/smartcheck
    entrypoint: "'$BIN/do_solidity' '$FILENAME' '$BIN'"
    solc: yes
    bin: scripts
