name: teEther
image: smartbugs/teether:04adf56
origin: https://github.com/nescio007/teether
version: '#04adf56'
info: Analysis and automatic exploitation framework for Ethereum smart contracts.
runtime:
    command: "'$FILENAME' 0x1234 0x1000 +1000"
