name: Conkas
origin: https://github.com/nveloso/conkas
version: "#6aee098"
info: Conkas analyzes Ethereum smart contracts to find potential security issues. It uses Rattle to lift the bytecode to an intermediate representation and then applies symbolic execution.
image: smartbugs/conkas
bin: scripts
solidity:
    entrypoint: "'$BIN/do_solidity' '$FILENAME' '$BIN'"
    solc: yes
runtime:
    entrypoint: "'$BIN/do_runtime' '$FILENAME' '$BIN'"
